---
title: "Media Optimization II"
format:
  html:
    code-fold: true
    code-summary: "Code"
---

```{r}
#| code-fold: true
#| code-summary: "Load libraries"
#| message: false

library(ggplot2)
library(ggthemes)
library(janitor)
library(magrittr)
library(dplyr)
library(caret)
library(RColorBrewer)
library(patchwork)
library(parallelPlot)
```

```{r}
#| code-fold: true
#| code-summary: "Retrieve & curate data"
#| message: false

df <- read.csv('../data/MediaOptimization_II.csv') %>% janitor::clean_names() %>% dplyr::select(-x)
```

```{r}
#| code-fold: true
#| code-summary: "Parallel plot"
#| message: false

q <- df %>%
mutate(plate_id = as.factor(plate_id)) %>%
mutate(media = as.factor(media)) %>%
mutate(inh_add1 = as.factor(inh_add1)) %>%
mutate(sm_af_or_add2 = as.factor(sm_af_or_add2)) %>%
mutate(add3 = as.factor(add3)) %>%
mutate(add4 = as.factor(add4))

qaz <- q %>%
dplyr::select(plate_id,
  strain,
  media,
  inh_add1,
   inh_add1_lvl_or_g_l,
   sm_af_or_add2,
   sm_s_or_add2_lvl,
   add3,
   add3_lvl,
   add4,
   add4_lvl,
   add5,
   add6_lvl,
   add7,
   add_7_lvl,
   od,
   side_product_1,
   downstream_intermediate_1,
   target_product,
   downstream_intermediate_2,
   side_product_2,
   downstream_intermediate_3,
   downstream_intermediate_4,
   side_product_3)

parallelPlot(qaz)
```